### PR TITLE
Fix drag and drop + element placement in level 2 activity

### PR DESCRIPTION
**Pull request by ashleyplusplus**
Component library was in the wrong spot and drag and drop didn't work correctly. This was due to the `img` elements inside the component containers not having their own `id` attributes. Adding these also helped with validation, allowing us to check whether the component dragged into a box was correct/allowed by checking that the img `id` was correct. Also, changed the size of boxes on the circuit to make things look more connected to the wire.

Additionally: fixed behavior regarding circuit validation and lightbulb turning on. Pressing "Test Your Circuit" now turns on lightbulb if correct components are in correct spots.

**Results:**
image

### CODE REVIEW

**Review by y1c1 — APPROVED** [review]
Looks great!

**Review by y1c1 — APPROVED** [review]
The test your circuit function looks great!

**Review by y1c1 — APPROVED** [review]
Looks good to me!

**Comment by BethJ-20** [comment]
Looks great!

**Pull request merged**
