### PR TITLE
Add component library and stars

### PR DESCRIPTION
**Pull request by y1c1**
**UPDATE:**
Component library has all components, components are centered, and box is scrollable. Also accidentally added stars in this PR; too annoying to undo and redo that.
image

**OLD:**
Screenshot 2024-04-04 114111

### CODE REVIEW

**Comment by Jsharp517** [comment]
Looks good

**Comment by y1c1** [comment]
Looks good to me!

**Comment by BethJ-20** [comment]
looks great!

**Comment by Jsharp517** [comment]
Looks good

**Pull request merged**
