### PR TITLE
Create survey html and css files

### PR DESCRIPTION
**Pull request by y1c1**
The Google form is scrollable with the home button at the left corner. A screenshot is attached to show what it looks like.
Screenshot 2024-03-26 125909

### CODE REVIEW

**Comment by Jsharp517** [comment]
Looks great. I like it a lot.

**Review by Jsharp517 — COMMENTED** [review]
Looks good. I like it a lot.

**Review by Jsharp517 — APPROVED** [review]
I approve

**Comment by BethJ-20** [comment]
Looks good I love the style continuance!

**Review by ashleyplusplus — APPROVED** [review]
lookin good

**Pull request merged**
